/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.metodista.TCCtex.telas;

import br.metodista.TCCtex.Conversor;
import br.metodista.TCCtex.Textuais;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Denis
 */
public class TelaTextuais extends javax.swing.JFrame {

    Textuais t;
    /**
     * Creates new form Textuais
     */
    public TelaTextuais() {
        initComponents();
        // Abre este jFrame no centro da tela
        this.setLocationRelativeTo(null); 
        buscaOdt.setCurrentDirectory(new File("TestesArquivos\\"));
        t = new Textuais();
        setDtm((javax.swing.table.DefaultTableModel)jTable1.getModel());
            getDtm().getDataVector();
       
    }
    
private javax.swing.table.DefaultTableModel dtm;
LinkedList<File> capitulos = new LinkedList<>();
File odtCapitulo, odtIntroducao, odtConclusao;
JFileChooser buscaOdt = new JFileChooser();

    private File selectArquivo(String mensagem){
        
        //Seleção apenas de arquivos Opendocument (extensão: .odt)
        buscaOdt.setFileFilter(new FileNameExtensionFilter("Opendocument \".odt\"", "odt"));
        buscaOdt.setAcceptAllFileFilterUsed(false);
        //Texto que aparece na seleção do arquivo.
        buscaOdt.setDialogTitle(mensagem);
        /* Abre a caixa de seleção de arquivo e verifica e cancela se 
         * botão cancel for pressionado*/
        if(buscaOdt.showOpenDialog(this)!= JFileChooser.APPROVE_OPTION){
        return null;
        }
        //Envia caminho completo do arquivo
        return buscaOdt.getSelectedFile().getAbsoluteFile();
        
    }
    
 //////////////////////////////////////////////////////////////////////////////////////////////////
    public boolean testarOdt(File arquivo){
        //pega nome do arquivo
    String nomeOdt = arquivo.getName().toString();
        //Verifica se nome termina com .odt
        if(nomeOdt.endsWith(".odt")){
            //Verifica se arquivo existe
             if(arquivo.exists()){
                 //se Existir retorna true
                 return true;
             }else{
                 //Se não existir: desmarca terminei caixa está parte
                getjCheckBox1().setSelected(false);
            JOptionPane.showMessageDialog(null, "Erro: Arquivo não encontrado!","ERRO",JOptionPane.ERROR_MESSAGE);
            return false;
            }
}else{  //Arquivo não tem extensão ".odt", erro
        JOptionPane.showMessageDialog(null, "Erro: Só são permitidos arquivos .odt","ERRO,",JOptionPane.ERROR_MESSAGE);
        jTCapitulo.setText("Selecione o Arquivo e clique em Adicionar");
        return false;
        }        
}
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jAdicionarCap = new javax.swing.JButton();
        jTCapitulo = new javax.swing.JTextField();
        jRemoverCap = new javax.swing.JButton();
        jAlterarCap = new javax.swing.JButton();
        jSelectCap = new javax.swing.JButton();
        jAbrirCap = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTIntroducao = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTConclusao = new javax.swing.JTextField();
        jSelectConc = new javax.swing.JButton();
        jAbrirConc = new javax.swing.JButton();
        jTermTextuais = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(167, 204, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(966, 830));
        jPanel1.setMinimumSize(new java.awt.Dimension(966, 830));
        jPanel1.setName("Informações Essenciais"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Capítulos:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Arquivo", "Caminho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(2).setMinWidth(25);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(25);
        }

        jAdicionarCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAdicionarCap.setText("Adicionar");
        jAdicionarCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdicionarCapActionPerformed(evt);
            }
        });

        jTCapitulo.setEditable(false);
        jTCapitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTCapitulo.setText("Selecione o Arquivo e clique em Adicionar");
        jTCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCapituloActionPerformed(evt);
            }
        });

        jRemoverCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRemoverCap.setText("Remover");
        jRemoverCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoverCapActionPerformed(evt);
            }
        });

        jAlterarCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAlterarCap.setText("Alterar");
        jAlterarCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarCapActionPerformed(evt);
            }
        });

        jSelectCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSelectCap.setText("...");
        jSelectCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectCapActionPerformed(evt);
            }
        });

        jAbrirCap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAbrirCap.setText("Abrir");
        jAbrirCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirCapActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("˄");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setText("˅");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jAbrirCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAlterarCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoverCap))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSelectCap)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jAdicionarCap))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCapitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdicionarCap)
                    .addComponent(jSelectCap))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAlterarCap)
                        .addComponent(jAbrirCap))
                    .addComponent(jRemoverCap))
                .addGap(11, 11, 11))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Introdução", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jTIntroducao.setEditable(false);
        jTIntroducao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTIntroducao.setText("Selecione o Arquivo de Introdução");
        jTIntroducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIntroducaoActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Abrir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTIntroducao, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIntroducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jButton8))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Conclusão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jTConclusao.setEditable(false);
        jTConclusao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTConclusao.setText("Selecione o Arquivo de Conclusão");

        jSelectConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSelectConc.setText("...");
        jSelectConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectConcActionPerformed(evt);
            }
        });

        jAbrirConc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAbrirConc.setText("Abrir");
        jAbrirConc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAbrirConcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSelectConc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAbrirConc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelectConc)
                    .addComponent(jAbrirConc))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTermTextuais.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTermTextuais.setText("Terminei esta parte");
        jTermTextuais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTermTextuaisActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Voltar");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Textuais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(jTermTextuais))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTermTextuais)
                .addGap(23, 23, 23)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salvar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Botão para Adicionar Capítulo a tabela
    private void jAdicionarCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarCapActionPerformed
try {   
        //pega nome do arquivo odt    
        String nomeOdt = odtCapitulo.getName().toString();
        if(nomeOdt.endsWith(".odt")){
              
           //Adiciona linha na tabela com numero do capitulo, nome e caminho
            getDtm().addRow(new Object[]{"Cap "+(getDtm().getRowCount()+1),odtCapitulo.getName(),odtCapitulo.getAbsolutePath()});
           
           //Apaga caminho do campo de texto jTCapitulo 
            jTCapitulo.setText("Selecione o Arquivo e clique em Adicionar");
            odtCapitulo = new File("");
        }
} catch (NullPointerException e) {
        }  

    }//GEN-LAST:event_jAdicionarCapActionPerformed
// Botão Selecione Cápitulo
    private void jSelectCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectCapActionPerformed
try {
    jTCapitulo.setText("Selecione o Arquivo e clique em Adicionar");
        //Seleciona arquivo odt pelo método selectArquivo()
        odtCapitulo = selectArquivo("Selecione o Capítulo");
        if(testarOdt(odtCapitulo)){
        //Escreve o caminho do arquivo no Campo de texto 
        jTCapitulo.setText(odtCapitulo.toString());
}else{
        jTCapitulo.setText("Selecione o Arquivo e clique em Adicionar");
        }
} catch (NullPointerException e) {
                   
//} catch (IOException ex) {
//    Logger.getLogger(TelaPreTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSelectCapActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
    jTIntroducao.setText("Selecione a Introdução");
//Seleciona arquivo odt pelo método selectArquivo()
        odtIntroducao = selectArquivo("Selecione a Introdução");
            getjTIntroducao().setText(odtIntroducao.toString());
        String nomeOdt = odtIntroducao.getName().toString();
        if(testarOdt(odtIntroducao)){
        //Escreve o caminho do arquivo no Campo de texto
        
        //Se o arquivo foi selecionado  
        }else{
                getjTIntroducao().setText("Selecione a Introdução");
        }
} catch (NullPointerException e) {
                   
//} catch (IOException ex) {
//    Logger.getLogger(TelaPreTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
// Botão selecionar Conclusão
    private void jSelectConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectConcActionPerformed
try {
        jTConclusao.setText("Selecione o Arquivo de Conclusão");
        //Seleciona arquivo odt pelo método selectArquivo()
        odtConclusao = selectArquivo("Selecione o Capítulo");
        if(testarOdt(odtConclusao)){
        //Escreve o caminho do arquivo no Campo de texto
                getjTConclusao().setText(odtConclusao.toString());
        //Se o arquivo foi selecionado  
    }else{
                getjTConclusao().setText("Selecione o Arquivo de Conclusão");
    }    
} catch (NullPointerException e) {
                   
//} catch (IOException ex) {
//    Logger.getLogger(TelaPreTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSelectConcActionPerformed

    private void jTermTextuaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTermTextuaisActionPerformed
File introducao, conclusao;
        
        
introducao = new File(getjTIntroducao().getText());
conclusao = new File(getjTConclusao().getText());
//Pega arquivo de introdução pelo campo de texto

if(getjCheckBox1().isSelected()){
        t.setIntroducao(introducao);

//Pega todos capitulos da tabela
        capitulos.clear();
        for(int i=0; i < getDtm().getRowCount(); i++){
        capitulos.add(new File(getDtm().getValueAt(i, 2)+""));
        }
        t.setCapitulos(capitulos);

        //Pega arquivo de conclusão pelo campo de texto
        t.setConclusao(conclusao);
        try {
            if(introducao.exists() && conclusao.exists()&&capitulos.get(0).exists()){
            t.converterTextuais();
            this.setVisible(false);
            TelaPrincipal.tela.getImagem3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/metodista/TCCtex/telas/imagens/certo.png")));
            
            
            String textuaisTex="";
            for( int i=0; i<ArquivosGerados().size(); i++){
                textuaisTex = textuaisTex+"\\input{"+ArquivosGerados().get(i)+"}\n";
            }
            Conversor c = new Conversor();
            textuaisTex = "\\textual \n"+textuaisTex; 
            File textual = new File("LaTex\\textual.tex");
                   c.escreverArquivo(textuaisTex, textual);
            
            
            TelaPrincipal.tela.setVisible(true);
            
            }else{
                JOptionPane.showMessageDialog(null, "Erro, insira todos arquivos obrigatórios,\n\n"
                        + "     - Introdução;\n"
                        + "     - Um Capítulo pelo menos;\n"
                        + "     - Conclusão.","ERRO",JOptionPane.ERROR_MESSAGE);
                getjCheckBox1().setSelected(false);
            }         
        } catch (IOException ex) {
            Logger.getLogger(TelaTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}else{
//apagar arquivos tex se gerados (não implementado)
    TelaPrincipal.tela.getImagem3().setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/metodista/TCCtex/telas/imagens/errado.png")));
    }
    }//GEN-LAST:event_jTermTextuaisActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setVisible(false);
        TelaPrincipal.tela.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTIntroducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIntroducaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIntroducaoActionPerformed

    private void jTCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCapituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCapituloActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     try {
            Runtime.getRuntime().exec("explorer "+jTIntroducao.getText());
        } catch (IOException ex) {
            Logger.getLogger(TelaPreTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jAbrirConcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirConcActionPerformed
         try {
            Runtime.getRuntime().exec("explorer "+jTConclusao.getText());
        } catch (IOException ex) {
            Logger.getLogger(TelaPreTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAbrirConcActionPerformed

    private void jAlterarCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarCapActionPerformed
        try{
        int selectedRow = jTable1.getSelectedRow();
            if(selectedRow >= 0){
        File capMod = selectArquivo("Selecione um novo Capitulo");
        dtm.setValueAt(capMod.getName(), (selectedRow), 1);
        dtm.setValueAt(capMod.getAbsoluteFile(), (selectedRow), 2);
            }
        }catch(NullPointerException e){
        // clicou no bot'ao cancelar
        }
    }//GEN-LAST:event_jAlterarCapActionPerformed

    private void jRemoverCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoverCapActionPerformed
   int selectedRow = jTable1.getSelectedRow();
        //Se linha foi selecionada(maior ou igual a zero)
        if(selectedRow >= 0){
            //remover linha
            dtm.removeRow(jTable1.getSelectedRow());
        //Recarregar numero de cada capitulo
            for(int row = 0; row < dtm.getRowCount(); row++){
        dtm.setValueAt("Cap "+(row+1), row, 0);
        }
   }
    }//GEN-LAST:event_jRemoverCapActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  int selectedRow = jTable1.getSelectedRow();
  try{
  if(selectedRow >= 0 && selectedRow < (dtm.getRowCount()-1)){
  String l11 = dtm.getValueAt(selectedRow, 1).toString();
  String l12 = dtm.getValueAt(selectedRow, 2).toString();
  String l21 = dtm.getValueAt((selectedRow+1), 1).toString();
  String l22 = dtm.getValueAt((selectedRow+1), 2).toString();
  //Coloca o valor da linha de baixo na linha de cima
  dtm.setValueAt(l21, selectedRow, 1);
  dtm.setValueAt(l22, selectedRow, 2);
  //Coloca o valor da linha de cima na linha de baixo
    dtm.setValueAt(l11, (selectedRow+1), 1);
    dtm.setValueAt(l12, (selectedRow+1), 2);
    jTable1.setRowSelectionInterval((selectedRow+1),1);
    
  }
  }catch (ArrayIndexOutOfBoundsException e){
  System.out.println("Erro: "+e);
  }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
  int selectedRow = jTable1.getSelectedRow();
  if(selectedRow > 0){
  String l11 = dtm.getValueAt(selectedRow, 1).toString();
  String l12 = dtm.getValueAt(selectedRow, 2).toString();
  String l21 = dtm.getValueAt((selectedRow-1), 1).toString();
  String l22 = dtm.getValueAt((selectedRow-1), 2).toString();
  //Coloca o valor da linha de baixo na linha de cima
  dtm.setValueAt(l21, selectedRow, 1);
  dtm.setValueAt(l22, selectedRow, 2);
  //Coloca o valor da linha de cima na linha de baixo
    dtm.setValueAt(l11, (selectedRow-1), 1);
    dtm.setValueAt(l12, (selectedRow-1), 2);
    jTable1.setRowSelectionInterval((selectedRow-1),1);
  }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jAbrirCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAbrirCapActionPerformed
      int selectedRow = jTable1.getSelectedRow();
        dtm.getValueAt(selectedRow,2);
        try {
            Runtime.getRuntime().exec("explorer "+dtm.getValueAt(selectedRow,2).toString());
        } catch (IOException ex) {
            Logger.getLogger(TelaTextuais.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAbrirCapActionPerformed
      //Resetar lista de capitulos
    public void resetCapitulos(){
        capitulos = new LinkedList<>();
    t.setCapitulos(capitulos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTextuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTextuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTextuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTextuais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTextuais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jAbrirCap;
    private javax.swing.JButton jAbrirConc;
    private javax.swing.JButton jAdicionarCap;
    private javax.swing.JButton jAlterarCap;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jRemoverCap;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSelectCap;
    private javax.swing.JButton jSelectConc;
    private javax.swing.JTextField jTCapitulo;
    private javax.swing.JTextField jTConclusao;
    private javax.swing.JTextField jTIntroducao;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox jTermTextuais;
    // End of variables declaration//GEN-END:variables

    public LinkedList<String> ArquivosGerados(){
    LinkedList<String> gerados = new LinkedList();
    gerados.add(new File(getjTIntroducao().getText()).getName().replace( ".odt", "" ));
    for(int i=0; i< capitulos.size(); i++){
    gerados.add(capitulos.get(i).getName().replace( ".odt", "" ));
    }
    gerados.add(new File(getjTConclusao().getText()).getName().replace( ".odt", "" ));
        return gerados;
    
    }
    
    /**
     * @return the jCheckBox1
     */
    public javax.swing.JCheckBox getjCheckBox1() {
        return jTermTextuais;
    }

    /**
     * @return the jTConclusao
     */
    public javax.swing.JTextField getjTConclusao() {
        return jTConclusao;
    }

    /**
     * @return the jTIntroducao
     */
    public javax.swing.JTextField getjTIntroducao() {
        return jTIntroducao;
    }

    /**
     * @return the dtm
     */
    public javax.swing.table.DefaultTableModel getDtm() {
        return dtm;
    }

    /**
     * @param dtm the dtm to set
     */
    public void setDtm(javax.swing.table.DefaultTableModel dtm) {
        this.dtm = dtm;
    }

    public void setjTIntroducao(String x) {
        this.jTIntroducao.setText(x);
    }
    
    public void setjTConclusao(String x) {
        this.jTConclusao.setText(x);
    }

    public void setjTCapitulo(String x) {
        this.jTCapitulo.setText(x);
    }

    public void limparTabela() {
       for (int i = 0; i<= dtm.getRowCount();i++){
       dtm.setNumRows(0);
       }
    }
}
